version: '3.8'
services:
  mysql:
    image: mysql
    ports:
      - "3309:3308"  
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev

  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ".:/workspace"
    links:
      - "mysql"

  app_test:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: mysql2://root:root@mysql/dev
    volumes:
      - ".:/workspace"
    depends_on:
      - mysql

volumes:
  dbdata:
  appdata: